name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build library
      run: npm run build

    - name: Check bundle size
      run: |
        echo "Checking bundle sizes..."
        echo "UMD build size: $(stat -c%s dist/microui.js | numfmt --to=iec-i --suffix=B --format="%.1f")"
        echo "Minified size: $(stat -c%s dist/microui.min.js | numfmt --to=iec-i --suffix=B --format="%.1f")" 
        echo "ES module size: $(stat -c%s dist/microui.esm.js | numfmt --to=iec-i --suffix=B --format="%.1f")"
        
        # Check if minified file is under 12KB (11KB target + buffer)
        SIZE=$(stat -c%s dist/microui.min.js)
        if [ $SIZE -gt 12288 ]; then
          echo "❌ Minified bundle too large: $(echo $SIZE | numfmt --to=iec-i --suffix=B --format="%.1f")"
          exit 1
        else
          echo "✅ Bundle size is acceptable: $(echo $SIZE | numfmt --to=iec-i --suffix=B --format="%.1f")"
        fi

    - name: Check build outputs
      run: |
        ls -la dist/
        test -f dist/microui.js
        test -f dist/microui.min.js
        test -f dist/microui.esm.js
